Avoid use of py3_dist
%py3_dist expansion contains a buggy %python3_version reference, causing
things like:

 DEBUG util.py:447:  Error: No Package found for python%python3_versiondist(setuptools) >= 16.0
 DEBUG util.py:447:  Error: No Package found for python%python3_versiondist(typing-extensions) >= 3.7.4

Signed-off-by: Yann Dirson <yann.dirson@vates.tech>